facturacion/urls.py
from django.conf.urls import url
from django.contrib import admin
from venta import views as venta_views

#   Nota para documento y nuevodocumento
# Crea un nuevo documento como nuevodocumento,
# Pero tiene otro form porque agrega campos,
# Como nacionalidad, los ultimos.
# Ademas agrega un default en IVA

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', venta_views.index, name="index"),
    url(r'^documentos/$', venta_views.documentos, name="documentos"),
    url(r'^nuevo-documento/$', venta_views.nuevodocumento_paso1, name="nuevo-documento"),
    url(r'^agregar-items/$', venta_views.agregaritems, name="agregar-items"),
    url(r'^agregar-item/(?P<documento>\d+)/$', venta_views.agregaritem, name="agregar-item"),

    url(r'^documento/$', venta_views.documento, name="documento"),
    url(r'^nuevodocumentos/$', venta_views.nuevodocumento_paso1, name="nuevodocumentos"),
    url(r'^servicios/$', venta_views.servicios, name="servicios"),
    url(r'^items/$', venta_views.items, name="items"),
    url(r'^nuevoitem/$', venta_views.nuevoitem, name="nuevoitem"),
    url(r'^eliminaritem/$', venta_views.eliminaritem, name="eliminaritem"),
    url(r'^editaritem/$', venta_views.editaritem, name="editaritem"),
    url('^accounts/', admin.site.urls),
    url('^clientes/', venta_views.clientes, name="clientes"),
    url('^editarcliente/$', venta_views.editarcliente, name="editarcliente"),
    url('^doeditcliente/$', venta_views.doeditcliente, name="doeditcliente"),
    url('^restorecli/$', venta_views.restorecliente, name="restorecliente"),
    url('^eliminarcliente/$', venta_views.eliminarcliente, name="eliminarcliente"),
    url(r'^continuardoc/(?P<doc_id>\d+)/$', venta_views.continuardoc, name="continuardoc"),
]

venta/models.py
# -*- coding: utf-8 -*-
# encoding:utf-8

from __future__ import unicode_literals
from django.contrib.auth.models import User

from django.db import models
from datetime import datetime

# CHOICES
IVA_CHOICES = (
    ('01', 'Responsable Inscripto'),
    ('02', 'Responsable no Inscripto'),
    ('03', 'No Responsable'),
    ('04', 'Exento'),
    ('05', 'Consumidor Final'),
    ('06', 'Monotributo'),
    ('07', 'No Categoriado'),
    ('08', 'Importador'),
    ('09', 'Exterior'),
    ('10', 'Liberado'),
    ('11', 'Responsable Inscripto - Agente de Percepción')
)

# Comenzado: Temporal, creado con o sin datos, debe tener
#           * cajero_emisor
#           * caja_emisora
#           * fecha_emision
#           * estado = Comenzado
ESTADO_DOCUMENTO_CHOICES = (
    ('01', 'Comenzado'),
    ('02', 'Finalizado'),
    ('03', 'Facturado')
)
# Create your models here.

class NonTrashManager(models.Manager):
    ''' Query only objects which have not been trashed. '''
    def get_query_set(self):
        query_set = super(NonTrashManager, self).get_query_set()
        return query_set.filter(trashed_at__isnull=True)


class TrashManager(models.Manager):
    ''' Query only objects which have been trashed. '''
    def get_query_set(self):
        query_set = super(TrashManager, self).get_query_set()
        return query_set.filter(trashed_at__isnull=False)


class Cliente(models.Model):
    razon_social = models.CharField(max_length=50, verbose_name="Razón Social")
    domicilio_comercial = models.CharField(max_length=100, verbose_name="Domicilio Comercial")
    condicion_iva = models.CharField(choices=IVA_CHOICES, verbose_name="Condición frente al IVA", max_length=2)
    cuit = models.CharField(max_length=13, verbose_name="CUIT")
    mail = models.CharField(max_length=50, verbose_name="e-mail")
    telefono = models.CharField(max_length=30, verbose_name=u'Teléfono')
    #Choices by pais
    nacionalidad = models.CharField(max_length=30, blank=True, null=True)

    #Variables para el restore
    #Obtenido de aca https://ltslashgt.com/2007/07/18/undelete-in-django/
    trashed_at = models.DateTimeField(blank=True, null=True)
    objects = NonTrashManager()
    trash = TrashManager()

    def delete(self, trash=True):
        if not self.trashed_at and trash:
            self.trashed_at = datetime.now()
            self.save()
        else:
            super(Cliente, self).delete()

    def restore(self, commit=True):
        self.trashed_at = None
        if commit:
            self.save()

    def __str__(self):
        if self.trashed_at:
            return '{} ({})'.format(self.razon_social, 'trashed')
        else:
            return self.razon_social

        #trashed = (self.trashed_at and 'trashed' or 'not trashed')
        #return '%s (%s)' % (self.razon_social, trashed)
        #return self.razon_social


class PuntoVenta(models.Model):
    numero = models.PositiveIntegerField(verbose_name="Número", unique=True)
    nombre = models.CharField(max_length=60, verbose_name="Nombre")
    crt = models.FileField(upload_to="certificados/", null=False, blank=False, verbose_name="CRT")
    key = models.FileField(upload_to="certificados/", null=False, blank=False, verbose_name="Private Key")
    razon_social = models.CharField(max_length=50, verbose_name="Razón Social")
    domicilio_comercial = models.CharField(max_length=100, verbose_name="Domicilio Comercial")
    condicion_iva = models.CharField(choices=IVA_CHOICES, verbose_name="Condición frente al IVA", max_length=2)
    cuit = models.CharField(max_length=13, verbose_name="CUIT")
    ingresos_brutos = models.CharField(max_length=20, verbose_name="Ingresos Brutos")
    inicio_actividades = models.CharField(max_length=15, verbose_name="Fecha Inicio Actividades")


    def __str__(self):
        return str(self.numero)


class Caja(models.Model):
    puntoVenta = models.ForeignKey(PuntoVenta, null=False, blank=False, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=60, verbose_name="Definición")

    def __str__(self):
        return self.nombre


class Cajero(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    caja = models.ForeignKey(Caja, null=False, blank=False, on_delete=models.CASCADE)
    nombre = models.CharField(max_length=70, null=False, blank=False)
    es_jefe_de_caja = models.BooleanField(verbose_name="Es Jefe de caja")
    es_administrador = models.BooleanField(verbose_name="Es Administrador general")

    def getCajeroByUser(cls, self, userid):
        usuario = User.objects.get(pk=userid)
        cajero = Cajero.objects.get(user=usuario)

        return cajero

    def __str__(self):
        return self.nombre


class TipoPago(models.Model):
    nombre = models.CharField(max_length=200, verbose_name="Definición")

    class Meta:
        verbose_name = "Tipo de Pago"
        verbose_name_plural = "Tipos de Pago"

    def __str__(self):
        return self.nombre


class Descuento(models.Model):
    nombre = models.CharField(max_length=200, verbose_name="Definición")
    porcentaje = models.DecimalField(max_digits=4, decimal_places=2)
    monto_fijo = models.IntegerField(verbose_name="Monto Fijo", blank=True, null=True)

    class Meta:
        verbose_name = "Descuento"
        verbose_name_plural = "Descuentos"

    def __str__(self):
        return self.nombre


class Item(models.Model):
    nombre = models.CharField(max_length=200, verbose_name="Nombre", blank=False, null=False)
    precio = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Precio de Lista", null=False,
                                 blank=False)
    precio_oferta = models.DecimalField(max_digits=8, decimal_places=2, verbose_name="Precio Oferta", null=True,
                                        blank=True)
    titulo_precio_oferta = models.CharField(max_length=80, null=True, blank=True)

    #Variables para el restore
    #Obtenido de aca https://ltslashgt.com/2007/07/18/undelete-in-django/
    trashed_at = models.DateTimeField(blank=True, null=True)
    objects = NonTrashManager()
    trash = TrashManager()

    def delete(self, trash=True):
        if not self.trashed_at and trash:
            self.trashed_at = datetime.now()
            self.save()
        else:
            super(Item, self).delete()

    def restore(self, commit=True):
        self.trashed_at = None
        if commit:
            self.save()

    def getPrecio(self):
        if self.precio_oferta > 0:
            return "* {} ({})".format(self.precio_oferta, self.titulo_precio_oferta)
        else:
            return self.precio

    def __str__(self):
        return self.nombre

    class Meta:
        verbose_name = "Producto o Servicio"
        verbose_name_plural = "Productos o Servicios"
        ordering = ("nombre",)

###
# DOS TIPOS DE DOCUEMNTOS: 1) RESERVAS, 2) VENTAS
# LAS VENTAS PUEDEN SER BLANCAS O NEGRAS. LAS BLANCAS TIENEN CAE. AL FACTURAR UNA VENTA SE EDITA EL REGISTRO DE VENTA
# EL CAMPO documento_relacionado CONTIENE LA RESERVA PARA CADA VENTA
class Documento(models.Model):
    cae = models.CharField(max_length=14, verbose_name="CAE", null=True, blank=True, default=None)
    pdf = models.FileField(upload_to="documentos/", null=True, blank=True, verbose_name="Archivo PDF")
    cajero_emisor = models.ForeignKey(Cajero, blank=False, null=False, on_delete=models.CASCADE)
    caja_emisora = models.ForeignKey(Caja, blank=False, null=False, on_delete=models.CASCADE)
    fecha_emision = models.DateTimeField(verbose_name="Fecha/Hora de emisión", auto_now_add=True)
    pago = models.ForeignKey(TipoPago, blank=False, null=True, on_delete=models.CASCADE)
    descuentos = models.ManyToManyField(Descuento, blank=True, null=True)
    documento_relacionado = models.ManyToManyField('self', verbose_name="Documento Relacionado", blank=True)
    estado = models.CharField(max_length=2, choices=ESTADO_DOCUMENTO_CHOICES)
    #Datos comprador
    #Campo relacional opcional por si decide guardar el cliente luego de realizar la factura, su función es la de autocomplete
    rel_cliente = models.ForeignKey(Cliente, verbose_name="Cliente", blank=True, null=True)
    razon_social = models.CharField(max_length=50, verbose_name="Razón Social", blank=True, null=True)
    domicilio_comercial = models.CharField(max_length=100, verbose_name="Domicilio Comercial", blank=True, null=True)
    condicion_iva = models.CharField(choices=IVA_CHOICES, verbose_name="Condición frente al IVA", max_length=2,
                                     blank=True, null=True)
    cuit = models.CharField(max_length=13, verbose_name="CUIT",
                            blank=True, null=True)

    ############# Totales #############
    # Total sumado de los items
    total_bruto = models.DecimalField(verbose_name="Total Bruto", max_digits=8, decimal_places=2,
                                      blank=True, null=True)
    # total_bruto con impuestos
    total_neto = models.DecimalField(verbose_name="Total", max_digits=8, decimal_places=2,
                                     blank=True, null=True)
    # total_bruto menos descuentos
    total = models.DecimalField(verbose_name="Total", max_digits=8, decimal_places=2,
                                blank=True, null=True)

    def __str__(self):
        return str(self.fecha_emision)

    # get documento OBJ
    # No pude devolver un objeto Documento   ## Frustrado  L:( ##
    def newTmpDocument(self, id):
        cajero = Cajero()
        self.cajero_emisor = Cajero.getCajeroByUser(cajero, id)
        return self

    def setCurrentConsFinal(self, request):
        self.cajero_emisor = Cajero.get(user = User.get(pkid=request.User.id))
        return self

class ItemDocumento(models.Model):
    documento = models.ForeignKey(Documento, on_delete=models.CASCADE)
    nota = models.CharField(max_length=20, blank=True)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)

venta/forms.py
# -*- coding: utf-8 -*-
from django import forms
from models import IVA_CHOICES
from models import Item
from models import Cliente
from models import ItemDocumento

class EncabezadoDocumentoForm(forms.Form):
    cuit = forms.CharField(max_length=13, label="CUIT")
    razon_social = forms.CharField(max_length=50, label="Razón Social")
    domicilio_comercial = forms.CharField(max_length=100, label="Domicilio Comercial")
    condicion_iva = forms.ChoiceField(choices=IVA_CHOICES, label="Condición frente al IVA")

class ItemDocumentoForm(forms.Form):
    nombre = forms.CharField(max_length=200, label="Nombre")
    precio = forms.DecimalField(max_digits=8, decimal_places=2, label="Precio de Lista")
    precio_oferta = forms.DecimalField(max_digits=8, decimal_places=2, label="Precio Oferta")

class AddItemForm(forms.ModelForm):
    class Meta:
        model = ItemDocumento
        fields = ["item", "cantidad", "descuentos", "nota"]

    # item = forms.ModelChoiceField(queryset=Item.objects.all(), label="Item")
    # cantidad = forms.IntegerField(label="Cantidad", min_value=1)
    # nota = forms.CharField(max_length=300, label="Nota", empty_value='', required=False )
    # descuento = forms.DecimalField(label="Descuento", max_value=100, min_value=0,max_digits=2,
    #                               decimal_places=1, required=False)

class ClienteForm(forms.ModelForm):

    class Meta:
        model = Cliente
        fields = ['cuit', 'razon_social', 'domicilio_comercial', 'condicion_iva', 'mail', 'telefono', 'nacionalidad']

class ItemForm(forms.ModelForm):

    class Meta:
        model = Item
        fields = ['nombre', 'precio', 'precio_oferta', 'titulo_precio_oferta']

class BuscarArticuloForm(forms.Form):
    nombre = forms.ModelChoiceField(queryset=Item.objects.all(),label="Item")

class BuscarClienteForm(forms.Form):
    cliente = forms.CharField(max_length="50")

venta/templates/agregar_items_factura.html
{% extends "index.html" %}
{% block header %}
		<!-- Header -->
			<header id="header">
				<a class="logo" href="/">Barolo Tours</a>
				<nav>
					<a href="#menu">Menu</a>
				</nav>
			</header>
{% endblock %}

{% block content%}
	<div class="inner">
		<div class="encabezado">
			<div class="encabezado_letra text-center">
				<h1 style="border: solid 1px #555; padding:5px 10px; width: 70px; margin: 0 auto 0 auto; text-align: center;">X</h1>
			</div>

<!--
			<div class="col-4">
				<div class="encabezado_izquierda">
					<ul class="alt">
						<li>Razón Social: {{doc.razon_social}}</li>
						<li>Domicilio Comercial: {{doc.domicilio_comercial}}</li>
						<li>Condición IVA: {{doc.condicion_iva}}</li>
					</ul>
				</div>
			</div>
-->
		</div>
	<hr />
	</div>
	<div class="table-wrapper">
		 <div class="inner">
            <div class="content">
                 <div class="row">
                 	<div class="col-8">
						<table class="alt">
							<thead>
								<tr>
									<th>Item</th>
									<th>Precio</th>
									<th>Cantidad</th>
									<th>Monto</th>
								</tr>
							</thead>
							{% for i in items %}
								<tbody>
									<tr>
										<td>{{ i.item }}</td>
										<td>{{ i.precio }}</td>
										<td>{{ i.cantidad }}</td>
										<td>{{ i.cantidad }}</td>
									</tr>
								</tbody>
							{% endfor %}
						</table>
						<div class="form">
							<form action="/agregar-item/{{documento.id}}/" method="post">
								{% csrf_token %}
								{{formAddItem}}
								<input type="submit" value="Agregar Item" class="button primary small"></input>
								<div style="padding-top:20px" class="actions">
									<ul class="actions">
										<li><a href="/cerrar-documento/" class="button small">Cerrar Documento</a></li>
										<li><a href="/cancelar-documento/" class="button small">Cancelar Documento</a></li>
									</ul>
								</div>
							</form>
						</div>

					</div>
				 </div>
			</div>
		</div>
	</div>
{% endblock %}

venta/templates/base.html
{% load staticfiles %}
<!DOCTYPE HTML>
<html>
	<head>
{% block head %}
		<title>Barolo Tours</title>
		<meta charset="utf-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1, user-scalable=no" />
		<meta name="description" content="" />
		<meta name="keywords" content="" />
		<link rel="stylesheet" href="{% static '' %}assets/css/main.css" />
{% endblock %}
{% block extra_head %}

{% endblock %}
	</head>

	<body class="is-preload">
{% block header %}
		<!-- Header -->
			<header id="header">
				<a class="logo" href="/">Barolo Tours [Principal]</a>
				<nav>
					<a href="#menu">Menu</a>
				</nav>
			</header>
{% endblock %}
{% block nav %}
		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="index.html">Home</a></li>
					<li><a href="elements.html">Elements</a></li>
					<li><a href="generic.html">Generic</a></li>
				</ul>
			</nav>
{% endblock%}
{% block content %}
		<!-- Highlights -->
			<section class="wrapper">
				<div class="inner">
					<div class="highlights">
						<section>
							<div class="content">
								<header>
									<a href="/clientes/" class="icon fa-vcard-o"><span class="label">Icon</span></a>
									<h3>Clientes</h3>
								</header>
								<p>Listado de clientes cargados en el sistema.</p>
							</div>
						</section>
						<section>
							<div class="content">
								<header>
									<a href="/documentos/" class="icon fa-files-o"><span class="label">Icon</span></a>
									<h3>Documentos</h3>
								</header>
								<p>Listado de documentos, estados y operaciones.</p>
							</div>
						</section>
						<section>
							<div class="content">
								<header>
									<a href="/items/" class="icon fa-floppy-o"><span class="label">Icon</span></a>
									<h3>Items</h3>
								</header>
								<p>Listado de items, productos o servicios.</p>
							</div>
						</section>
						<section>
							<div class="content">
								<header>
									<a href="#" class="icon fa-line-chart"><span class="label">Icon</span></a>
									<h3>Estadísticas</h3>
								</header>
								<p>Estadísticas de ventas.</p>
							</div>
						</section>
						<section>
							<div class="content">
								<header>
									<a href="#" class="icon fa-paper-plane-o"><span class="label">Icon</span></a>
									<h3>Comunicación</h3>
								</header>
								<p>Comunicación con clientes y vendedores.</p>
							</div>
						</section>
						<section>
							<div class="content">
								<header>
									<a href="#" class="icon fa-qrcode"><span class="label">Icon</span></a>
									<h3>Claves AFIP</h3>
								</header>
								<p>Claves y firmas digitales.</p>
							</div>
						</section>
					</div>
				</div>
			</section>

{% endblock %}

{% block footer %}
		<!-- Footer -->
			<footer id="footer">
				<div class="inner">
					<div class="content">
					</div>
					<div class="copyright">
						&copy; Sistema de ventas. Powered by <a href="https://www.estudiomanta.com">Manta</a>
					</div>
				</div>
			</footer>
{% endblock %}
{% block scripts %}
		<!-- Scripts -->
			<script src="{% static '' %}assets/js/jquery.min.js"></script>
			<script src="{% static '' %}assets/js/browser.min.js"></script>
			<script src="{% static '' %}assets/js/breakpoints.min.js"></script>
			<script src="{% static '' %}assets/js/util.js"></script>
			<script src="{% static '' %}assets/js/main.js"></script>
{% endblock %}
	</body>
</html>

venta/templates/editar_cliente.html
{% extends "index.html" %}

{% block content%}

    <div class="table-wrapper">
        <div class="inner">
            <div class="content">
<h2>Editar Cliente</h2>
<h4><i class="icon fa-exclamation-triangle"></i>
	{% if request.GET.id %}
		{{ mensaje }}
	{% else %}
		Listado de clientes
	{% endif %}
</h4>
</div></div></div>


	<div class="table-wrapper">
		<div class="inner">
			<form action="/doeditcliente/?id={{cliente.id}}" method="post">
				{% csrf_token %}
				{{ form }}
				<p>
					<div class="col-12">
						<ul class="actions">
							<li><button type="submit" class="button fit small icon fa-hdd-o" style="float:left width:50%">Grabar</button></li>
							<li><a href="/clientes/" class="button fit small icon fa-times">Cancelar</a></li>
						</ul>
					</div>
				</p>
			</form>
		</div>
	</div>
{% endblock %}

venta/templates/editar_item.html
{% extends "index.html" %}

{% block content%}

    <div class="table-wrapper">
        <div class="inner">
            <div class="content">
<h2>Editar Item</h2>
<h3>
	{% if request.GET.id %}
		{{ mensaje }}
	{% else %}
		Listado de Productos y Servicios
	{% endif %}
</h3>

</div></div></div>

	<div class="table-wrapper">
		<div class="inner">
			<form action="/editaritem/?id={{item.id}}" method="post">
				{% csrf_token %}
				{{ form }}
				<p>
					<div class="col-12">
						<ul class="actions">
							<li><button type="submit" class="button fit small icon fa-hdd-o" style="float:left width:50%">Grabar</button></li>
							<li><a href="/items/" class="button fit small icon fa-times">Cancelar</a></li>
						</ul>
					</div>
				</p>
				<input type="hidden" name="doedit" value="1" />
			</form>
		</div>
	</div>
{% endblock %}

venta/templates/encabezado_documento.html
{% extends "index.html" %}

{% block content%}

    <div class="table-wrapper">
        <div class="inner">
            <div class="content">
                <div class="col-10"><h2 class="center-text">Crear Nuevo Documento</h2></div>
            </div>
        </div>
    </div>    

	<div class="table-wrapper">
        <div class="inner">
            <div class="content">
            <div class="col-6 col-12-medium">
                <h3>Para Consumidor Final:</h3>
                <a href="" class="button small">Generar Documento</a>
            </div>
            <hr/>
            <div class="col-6 col-12-medium">
                <h3>Agregar Items sin Cliente:</h3>
                <a href="/agregar-items/" class="button small">Generar Documento</a>
            </div>
            <hr/>
            <div class="col-6 col-12-medium" style="margin-top:30px;" >
                <h3>Para otro tipo de cliente, complete el formulario:</h3>
                <form action="/agregar-items/" method="post">
                    {% csrf_token %}
                    {{ form }}
                    <input type="submit" value="Siguiente >" />
                    <input type="hidden" value="step1" />
                </form>
            </div>
       <ul class="actions">
        <li><a href="/documentos/" class="button small">Cancelar / Volver</a></li>
       </ul>

            </div>
        </div>
	</div>


{% endblock %}

venta/templates/index.html
{% extends "base.html" %}

{% block nav %}
		<!-- Nav -->
			<nav id="menu">
				<ul class="links">
					<li><a href="/">Inicio</a></li>
					<li><a href="/documentos/">Documentos</a></li>
					<li><a href="/clientes/">Clientes</a></li>
					<li><a href="/items/">Productos y servicios</a></li>
				</ul>
			</nav>
{% endblock%}

venta/templates/listado_clientes.html
{% extends "index.html" %}

{% block content%}
    <div class="table-wrapper">
        <div class="inner">
            <div class="content">

<h2>
	{% if mensaje %}
		{{ mensaje }}
		{% if clitrash %}
			<a href="/restorecli/?idclitrash={{clitrash}}" class="button fa fa-arrow-left">restore</a>
		{% endif%}
	{% else %}
		Listado de clientes
	{% endif %}
</h2>
	<ul class="actions">
		<li><a href="/clientes/" class="button primary small">Listado de Clientes</a></li>
	</ul>

</div></div></div>

	<div class="inner">
		<table class="alt">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Cuit</th>
					<th>IVA</th>
					<th>email</th>
					<th>Domicilio</th>
					<th></th>
					<th></th>
				</tr>
			</thead>
{% for c in clientes %}
			<tbody>
				<tr>
					<td>{{ c.razon_social }}</td>
					<td>{{ c.cuit }}</td>
					<td>{{ c.get_condicion_iva_display }}</td>
					<td>{{ c.mail }}</td>
					<td>{{ c.domicilio_comercial }}</td>
					<td>
						<a href="/editarcliente?id={{ c.id }}" class="button fit small icon fa-pencil">Editar</a>
					</td>
					<td>
						<a href="/eliminarcliente?id={{ c.id }}" class="button fit small icon fa-trash">Eliminar</a>
					</td>
				</tr>
			</tbody>
{% endfor %}

			<tfoot>
				<tr>
					<td colspan="5"></td>
				</tr>
			</tfoot>
		</table>
	</div>


{% endblock %}

venta/templates/listado_documentos.html
{% extends "index.html" %}

{% block header %}
	<!-- Header -->
	<header id="header">
		<a class="logo" href="/">Barolo Tours. [Inicio]</a>
		<nav>
			<a href="#menu">Menu</a>
		</nav>
	</header>
{% endblock %}

{% block content%}
    <div class="table-wrapper">
        <div class="inner">
            <div class="content">

<h2>Documentos</h2>

	<ul class="actions">
		<li><a href="#" class="button primary small">Listado</a></li>
		<li><a href="/nuevo-documento/" class="button small">Nuevo Documento</a></li>
		<li><a href="#" class="button small">Filtros</a></li>
	</ul>

   </div></div></div>
	<div class="inner">
	<div class="table-wrapper">
		<table class="alt">
			<thead>
				<tr>
					<th>Número</th>
					<th>Fecha</th>
					<th>Destinatario</th>
					<th>Cajero</th>
					<th>Estado</th>
					<th>Importe Total</th>
					<th>Continuar</th>
					<th>Ver/Imprimir</th>
					<th>Facturar</th>
				</tr>
			</thead>
{% for d in documentos %}
			<tbody>
				<tr>
					<td>{{ d.id }}</td>
					<td>{{ d.fecha_emision }}</td>
					<td>{{ d.razon_social }}</td>
					<td>{{ d.cajero }}</td>
					<td>{{ d.get_estado_display }}</td>
					<td>{{ d.total }}</td>
<!--					<td><a href="/agregaritems/id={{d.id}}" style="button">Continuar</a></td>-->
					<td><a href="/continuardoc/{{d.id}}/" class="button fit small icon fa-pencil">Continuar</a></td>
					<td><a class="button  fit small icon fa-print">Ver</a></td>
					<td><a class="button fit small icon fa-document">Facturar</a></td>
				</tr>
			</tbody>
{% endfor %}

		</table>
	</div>
    </div>


{% endblock %}

venta/templates/listado_servicios.html
{% extends "index.html" %}

{% block content%}

<h4>Servicios</h4>

	<div class="table-wrapper">
		<table class="alt">
			<thead>
				<tr>
					<th>Nombre</th>
					<th>Nombre</th>
					<th>Importe</th>
					<th>Descuento</th>
				</tr>
			</thead>
{% for s in servicios %}
			<tbody>
				<tr>
					<td>{{ s.id }}</td>
					<td>{{ s.nombre }}</td>
					<td>{{ s.precio }}</td>
					<td>{{ s.precio_oferta }}</td>
				</tr>
			</tbody>
{% endfor %}

			<tfoot>
				<tr>
					<td colspan="2"></td>
					<td>360.00</td>
				</tr>
			</tfoot>
		</table>
	</div>


{% endblock %}

venta/templates/sumar-articulo-1.html
{% extends "index.html" %}

{% block content%}
<h3>
	Agregar Articulo al documentos {{numdoc}}
</h3>
	<ul class="actions">
		<li><a href="/continuardoc/{{numdoc}}/" class="button primary small">Volver al Documento</a></li>
	</ul>

	<div class="inner">

        <form method="POST" action="/agregaritems/"

	</div>


{% endblock %}